#!/usr/local/bin/python3
import csv
from sys import argv, exit
from os.path import exists


def main():
    if len(argv) != 2:
        print("Usage: ./read <filename>.csv")
        exit(1)

    else:
        if exists(argv[1]):
            read(argv[1])
        else:
            print("File do not exists.")
            exit(1)


def read(filename):
    with open(filename, "r") as csvfile:
        reader = csv.reader(csvfile)

        for row in reader:
            num = len(row)

        maxlist = [0 * i for i in range(num)]

        for i in range(num):
            rewind(csvfile)
            maxlist[i] = 0

            for row in reader:
                if len(row[i]) > maxlist[i]:
                    maxlist[i] = len(row[i])

        rewind(csvfile)
        for row in reader:
            for i in range(num):

                print(row[i] + " " * (maxlist[i] - len(row[i])), sep="", end="")

                if i < num - 1:
                    print("|", end="")

                else:
                    print()
            
            for i in range(num):
                print(maxlist[i] * "-", end="")
                if i < num - 1:
                    print("|", end="")
                else:
                    print()

def rewind(filename):
    filename.seek(0)

main()