#!/usr/local/bin/python3

# THATS THE WAY TO MAKE THE FILE EXECUTABLE
# also remember you can do hard links
# and if you type that thing at the top file in the IDE will be recognized as Python
from sys import exit
from time import sleep

def gold_room():
    print("This room is full of gold. How much do you take?")

    choice = input("> ")
    # here we check if there is 0 at string choice, so 400 or 5043 will fit
    if choice.isdigit():
        how_much = int(choice)
    else:
        dead("Man, learn how to type a number.")

    if how_much < 50:
        print("Nice, you're not greedy, you win!")
        exit(0)
    else:
        dead("You greedy bastard!")


def bear_room():
    print("There is a bear here.")
    print("The bear har a bunch of honey.")
    print("The fat bear is in front of another door.")
    print("How are you going to move the bear?")
    bear_moved = False

    while True:
        choice = input("> ")

        if choice == "take honey":
            dead("The bear looks at yu then slaps you face off.")
        elif choice == "taunt bear" and not bear_moved: # look you do not have to use parentheses
            print("The bear has moved from the door.")
            print("You can go through it now.")
            bear_moved = True
        elif choice == "taunt bear" and bear_moved:
            dead("The bear gets pissed off and chews you leg off.")
        elif choice == "open door" and bear_moved:
            gold_room()
        else:
            print("I got no idea what that means.")

def cthulhu_room():
    print("Here you see the great evil Cthulhu.")
    print("He, it, whatever stares at you and you go insane.")
    print("Do you flee your life or eat your head?")

    choice = input("> ")

    if "flee" in choice:
        start()
    elif "head" in choice:
        dead("Well, that was tasty!")
    else:
        cthulhu_room()


def dead(why):
    print(why, "Good job!")
    exit(0)

def start():
    print("You are in a dark room.")
    print("There is a door to your right and left.")
    print("Which one do you take?")

    choice = input("> ")

    if choice == "left":
        bear_room()
    elif choice == "right":
        cthulhu_room()
    else:
        print("You stumble around the room until you starve.")
        for i in range(9):
            print('.', end='')
            sleep(1)
            if (i + 1) % 3 == 0:
                print()
        print("You resurrected!")
        sleep(3)
        print("Oh shit. Here we go again.")
        sleep(3)
        start()


start()
